# ==========================================
# Application Server Config
# ==========================================
server.port=8081

# ==========================================
# Kafka Consumer Configuration
# ==========================================
kafka.bootstrap.servers=localhost:9092
kafka.topic=log-events
kafka.consumer.group.id=rules-evaluator-group

# ==========================================
# Database Configuration (PostgreSQL)
# ==========================================
postgres.host=localhost
postgres.port=5433
postgres.database=log_monitor
postgres.username=log_monitor_user
postgres.password=log_monitor_password

# HikariCP Connection Pool Configs
postgres.pool.max-size=10
postgres.pool.min-idle=2
postgres.pool.connection-timeout-ms=30000