########################################
# Kafka Configuration
########################################

kafka.bootstrap.servers=localhost:9092
kafka.topic=log-events

########################################
# Log Directory
########################################

log.directory=logs
