########################################
# Kafka Configuration
########################################

kafka.bootstrap.servers=localhost:9092
kafka.topic=log-events
kafka.consumer.group.id=rules-evaluator

########################################
# PostgreSQL Configuration
########################################

postgres.host=localhost
postgres.port=5432
postgres.database=log_monitor
postgres.username=log_monitor_user
postgres.password=log_monitor_password


########################################
# Log Directory
########################################

log.directory=logs


########################################
# Rule Engine Configuration
########################################

rules.file=config/rules.json


########################################
# General Application Configuration
########################################

application.timezone=UTC